CREATE DATABASE hycon_db;
CREATE USER hycon_user WITH ENCRYPTED PASSWORD 'HyconCompany2026!';
GRANT ALL PRIVILEGES ON DATABASE hycon_db TO hycon_user;
ALTER DATABASE hycon_db OWNER TO hycon_user;
\c hycon_db
GRANT ALL ON SCHEMA public TO hycon_user;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO hycon_user;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO hycon_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO hycon_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO hycon_user;