"""initial_postgresql_schema

Revision ID: 940f138e40e3
Revises: 
Create Date: 2025-12-06 16:08:10.002831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '940f138e40e3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('description_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('usage_count', sa.Integer(), nullable=True),
    sa.Column('last_used', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('description')
    )
    op.create_index(op.f('ix_description_history_id'), 'description_history', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'EMPLOYEE', name='userrole'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('equipment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('equipment_id', sa.String(length=50), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('current_status', sa.Enum('AVAILABLE', 'IN_USE', 'MAINTENANCE', name='equipmentstatus'), nullable=True),
    sa.Column('current_user_id', sa.Integer(), nullable=True),
    sa.Column('current_session_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['current_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_equipment_location_status', 'equipment', ['location', 'current_status'], unique=False)
    op.create_index('idx_equipment_status_name', 'equipment', ['current_status', 'name'], unique=False)
    op.create_index(op.f('ix_equipment_created_at'), 'equipment', ['created_at'], unique=False)
    op.create_index(op.f('ix_equipment_current_status'), 'equipment', ['current_status'], unique=False)
    op.create_index(op.f('ix_equipment_current_user_id'), 'equipment', ['current_user_id'], unique=False)
    op.create_index(op.f('ix_equipment_equipment_id'), 'equipment', ['equipment_id'], unique=True)
    op.create_index(op.f('ix_equipment_id'), 'equipment', ['id'], unique=False)
    op.create_index(op.f('ix_equipment_location'), 'equipment', ['location'], unique=False)
    op.create_index(op.f('ix_equipment_name'), 'equipment', ['name'], unique=False)
    op.create_table('usage_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('planned_end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'COMPLETED', name='sessionstatus'), nullable=True),
    sa.Column('is_past_usage_log', sa.Boolean(), nullable=True),
    sa.Column('scientist_signature', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('end_time IS NULL OR end_time > start_time', name='check_end_after_start'),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_session_equipment_status', 'usage_sessions', ['equipment_id', 'status'], unique=False)
    op.create_index('idx_session_equipment_time', 'usage_sessions', ['equipment_id', 'start_time', 'end_time'], unique=False)
    op.create_index('idx_session_status_start', 'usage_sessions', ['status', 'start_time'], unique=False)
    op.create_index('idx_session_user_status', 'usage_sessions', ['user_id', 'status'], unique=False)
    op.create_index(op.f('ix_usage_sessions_created_at'), 'usage_sessions', ['created_at'], unique=False)
    op.create_index(op.f('ix_usage_sessions_end_time'), 'usage_sessions', ['end_time'], unique=False)
    op.create_index(op.f('ix_usage_sessions_equipment_id'), 'usage_sessions', ['equipment_id'], unique=False)
    op.create_index(op.f('ix_usage_sessions_id'), 'usage_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_usage_sessions_is_past_usage_log'), 'usage_sessions', ['is_past_usage_log'], unique=False)
    op.create_index(op.f('ix_usage_sessions_planned_end_time'), 'usage_sessions', ['planned_end_time'], unique=False)
    op.create_index(op.f('ix_usage_sessions_start_time'), 'usage_sessions', ['start_time'], unique=False)
    op.create_index(op.f('ix_usage_sessions_status'), 'usage_sessions', ['status'], unique=False)
    op.create_index(op.f('ix_usage_sessions_user_id'), 'usage_sessions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usage_sessions_user_id'), table_name='usage_sessions')
    op.drop_index(op.f('ix_usage_sessions_status'), table_name='usage_sessions')
    op.drop_index(op.f('ix_usage_sessions_start_time'), table_name='usage_sessions')
    op.drop_index(op.f('ix_usage_sessions_planned_end_time'), table_name='usage_sessions')
    op.drop_index(op.f('ix_usage_sessions_is_past_usage_log'), table_name='usage_sessions')
    op.drop_index(op.f('ix_usage_sessions_id'), table_name='usage_sessions')
    op.drop_index(op.f('ix_usage_sessions_equipment_id'), table_name='usage_sessions')
    op.drop_index(op.f('ix_usage_sessions_end_time'), table_name='usage_sessions')
    op.drop_index(op.f('ix_usage_sessions_created_at'), table_name='usage_sessions')
    op.drop_index('idx_session_user_status', table_name='usage_sessions')
    op.drop_index('idx_session_status_start', table_name='usage_sessions')
    op.drop_index('idx_session_equipment_time', table_name='usage_sessions')
    op.drop_index('idx_session_equipment_status', table_name='usage_sessions')
    op.drop_table('usage_sessions')
    op.drop_index(op.f('ix_equipment_name'), table_name='equipment')
    op.drop_index(op.f('ix_equipment_location'), table_name='equipment')
    op.drop_index(op.f('ix_equipment_id'), table_name='equipment')
    op.drop_index(op.f('ix_equipment_equipment_id'), table_name='equipment')
    op.drop_index(op.f('ix_equipment_current_user_id'), table_name='equipment')
    op.drop_index(op.f('ix_equipment_current_status'), table_name='equipment')
    op.drop_index(op.f('ix_equipment_created_at'), table_name='equipment')
    op.drop_index('idx_equipment_status_name', table_name='equipment')
    op.drop_index('idx_equipment_location_status', table_name='equipment')
    op.drop_table('equipment')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_description_history_id'), table_name='description_history')
    op.drop_table('description_history')
    # ### end Alembic commands ###