"""add_sample_submissions_and_email_recipients

Revision ID: b4b3676cc8c3
Revises: 940f138e40e3
Create Date: 2025-12-06 22:01:44.960445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4b3676cc8c3'
down_revision = '940f138e40e3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_recipients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_recipients_email'), 'email_recipients', ['email'], unique=True)
    op.create_index(op.f('ix_email_recipients_id'), 'email_recipients', ['id'], unique=False)
    op.create_index(op.f('ix_email_recipients_is_active'), 'email_recipients', ['is_active'], unique=False)
    op.create_table('sample_submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project', sa.String(length=100), nullable=False),
    sa.Column('sample_name', sa.String(length=200), nullable=False),
    sa.Column('batch_no', sa.String(length=100), nullable=False),
    sa.Column('label_claim', sa.String(length=200), nullable=False),
    sa.Column('sample_quantity', sa.String(length=100), nullable=False),
    sa.Column('packaging_configuration', sa.String(length=200), nullable=False),
    sa.Column('recommended_storage', sa.String(length=100), nullable=False),
    sa.Column('condition', sa.String(length=100), nullable=False),
    sa.Column('tests_to_be_performed', sa.Text(), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('submitted_to', sa.String(length=200), nullable=False),
    sa.Column('submitted_by', sa.String(length=200), nullable=False),
    sa.Column('submitted_by_user_id', sa.Integer(), nullable=True),
    sa.Column('recipient_email', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['submitted_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_submission_project_date', 'sample_submissions', ['project', 'created_at'], unique=False)
    op.create_index(op.f('ix_sample_submissions_created_at'), 'sample_submissions', ['created_at'], unique=False)
    op.create_index(op.f('ix_sample_submissions_id'), 'sample_submissions', ['id'], unique=False)
    op.create_index(op.f('ix_sample_submissions_project'), 'sample_submissions', ['project'], unique=False)
    op.create_index(op.f('ix_sample_submissions_submitted_by_user_id'), 'sample_submissions', ['submitted_by_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sample_submissions_submitted_by_user_id'), table_name='sample_submissions')
    op.drop_index(op.f('ix_sample_submissions_project'), table_name='sample_submissions')
    op.drop_index(op.f('ix_sample_submissions_id'), table_name='sample_submissions')
    op.drop_index(op.f('ix_sample_submissions_created_at'), table_name='sample_submissions')
    op.drop_index('idx_submission_project_date', table_name='sample_submissions')
    op.drop_table('sample_submissions')
    op.drop_index(op.f('ix_email_recipients_is_active'), table_name='email_recipients')
    op.drop_index(op.f('ix_email_recipients_id'), table_name='email_recipients')
    op.drop_index(op.f('ix_email_recipients_email'), table_name='email_recipients')
    op.drop_table('email_recipients')
    # ### end Alembic commands ###