"""add_composite_indexes_and_constraints

Revision ID: 21d28830d439
Revises: b78f1153e04d
Create Date: 2025-11-29 21:40:47.815170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21d28830d439'
down_revision = 'b78f1153e04d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create indexes for equipment table
    op.create_index('idx_equipment_location_status', 'equipment', ['location', 'current_status'], unique=False)
    op.create_index('idx_equipment_status_name', 'equipment', ['current_status', 'name'], unique=False)
    op.create_index(op.f('ix_equipment_created_at'), 'equipment', ['created_at'], unique=False)
    op.create_index(op.f('ix_equipment_current_status'), 'equipment', ['current_status'], unique=False)
    op.create_index(op.f('ix_equipment_current_user_id'), 'equipment', ['current_user_id'], unique=False)
    op.create_index(op.f('ix_equipment_location'), 'equipment', ['location'], unique=False)
    op.create_index(op.f('ix_equipment_name'), 'equipment', ['name'], unique=False)
    
    # Use batch mode for SQLite to handle foreign key changes
    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.drop_constraint('equipment_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key('fk_equipment_current_user', 'users', ['current_user_id'], ['id'], ondelete='SET NULL')
    
    # Create indexes for usage_sessions table
    op.create_index('idx_session_equipment_status', 'usage_sessions', ['equipment_id', 'status'], unique=False)
    op.create_index('idx_session_equipment_time', 'usage_sessions', ['equipment_id', 'start_time', 'end_time'], unique=False)
    op.create_index('idx_session_status_start', 'usage_sessions', ['status', 'start_time'], unique=False)
    op.create_index('idx_session_user_status', 'usage_sessions', ['user_id', 'status'], unique=False)
    op.create_index(op.f('ix_usage_sessions_created_at'), 'usage_sessions', ['created_at'], unique=False)
    op.create_index(op.f('ix_usage_sessions_end_time'), 'usage_sessions', ['end_time'], unique=False)
    op.create_index(op.f('ix_usage_sessions_equipment_id'), 'usage_sessions', ['equipment_id'], unique=False)
    op.create_index(op.f('ix_usage_sessions_planned_end_time'), 'usage_sessions', ['planned_end_time'], unique=False)
    op.create_index(op.f('ix_usage_sessions_start_time'), 'usage_sessions', ['start_time'], unique=False)
    op.create_index(op.f('ix_usage_sessions_status'), 'usage_sessions', ['status'], unique=False)
    op.create_index(op.f('ix_usage_sessions_user_id'), 'usage_sessions', ['user_id'], unique=False)
    
    # Use batch mode for SQLite to handle foreign key changes
    with op.batch_alter_table('usage_sessions', schema=None) as batch_op:
        batch_op.drop_constraint('usage_sessions_ibfk_1', type_='foreignkey')
        batch_op.drop_constraint('usage_sessions_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key('fk_session_user', 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('fk_session_equipment', 'equipment', ['equipment_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Use batch mode for SQLite to handle foreign key changes
    with op.batch_alter_table('usage_sessions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_session_equipment', type_='foreignkey')
        batch_op.drop_constraint('fk_session_user', type_='foreignkey')
        batch_op.create_foreign_key('usage_sessions_ibfk_2', 'equipment', ['equipment_id'], ['id'])
        batch_op.create_foreign_key('usage_sessions_ibfk_1', 'users', ['user_id'], ['id'])
    
    # Drop usage_sessions indexes
    op.drop_index(op.f('ix_usage_sessions_user_id'), table_name='usage_sessions')
    op.drop_index(op.f('ix_usage_sessions_status'), table_name='usage_sessions')
    op.drop_index(op.f('ix_usage_sessions_start_time'), table_name='usage_sessions')
    op.drop_index(op.f('ix_usage_sessions_planned_end_time'), table_name='usage_sessions')
    op.drop_index(op.f('ix_usage_sessions_equipment_id'), table_name='usage_sessions')
    op.drop_index(op.f('ix_usage_sessions_end_time'), table_name='usage_sessions')
    op.drop_index(op.f('ix_usage_sessions_created_at'), table_name='usage_sessions')
    op.drop_index('idx_session_user_status', table_name='usage_sessions')
    op.drop_index('idx_session_status_start', table_name='usage_sessions')
    op.drop_index('idx_session_equipment_time', table_name='usage_sessions')
    op.drop_index('idx_session_equipment_status', table_name='usage_sessions')
    
    # Use batch mode for SQLite to handle foreign key changes
    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.drop_constraint('fk_equipment_current_user', type_='foreignkey')
        batch_op.create_foreign_key('equipment_ibfk_1', 'users', ['current_user_id'], ['id'])
    
    # Drop equipment indexes
    op.drop_index(op.f('ix_equipment_name'), table_name='equipment')
    op.drop_index(op.f('ix_equipment_location'), table_name='equipment')
    op.drop_index(op.f('ix_equipment_current_user_id'), table_name='equipment')
    op.drop_index(op.f('ix_equipment_current_status'), table_name='equipment')
    op.drop_index(op.f('ix_equipment_created_at'), table_name='equipment')
    op.drop_index('idx_equipment_status_name', table_name='equipment')
    op.drop_index('idx_equipment_location_status', table_name='equipment')
    # ### end Alembic commands ###