"""Add planned_end_time to UsageSession

Revision ID: b78f1153e04d
Revises: 
Create Date: 2025-11-08 17:07:59.344855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b78f1153e04d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usage_sessions', sa.Column('planned_end_time', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usage_sessions', 'planned_end_time')
    # ### end Alembic commands ###